// mainReducer
export const FETCH_USER = "FETCH_USER";
export const FAILED_FETCH_USER = "FAILED_FETCH_USER";
export const SET_USER = "SET_USER";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const CHANGE_MOBILE_MENU = "CHANGE_MOBILE_MENU";
export const SET_DESIGN_TAB = "SET_DESIGN_TAB";
export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const SET_ACTIVE_TEMPLATES_CATEGORY = "SET_ACTIVE_TEMPLATES_CATEGORY";
export const TOGGLE_TEMPLATES_MODAL = "TOGGLE_TEMPLATES_MODAL";
export const TOGGLE_PRO_TEMPLATES_MODAL = "TOGGLE_PRO_TEMPLATES_MODAL";
export const SET_PRO_TEMPLATES_MODAL_PREVIEW =
  "SET_PRO_TEMPLATES_MODAL_PREVIEW";
export const TOGGLE_PRO_ELEMENTS_MODAL = "TOGGLE_PRO_ELEMENTS_MODAL";
export const SET_PRO_ELEMENTS_MODAL_PREVIEW = "SET_PRO_ELEMENTS_MODAL_PREVIEW";
export const CHANGE_TEMPLATES_SEARCH_TERM = "CHANGE_TEMPLATES_SEARCH_TERM";
export const CHANGE_LANG = "CHANGE_LANG";
export const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL";
export const CHANGE_AUTH_FORM = "CHANGE_AUTH_FORM";
export const SET_AFTER_AUTH_REDIRECT = "AFTER_AUTH_ACTION";
export const TOGGLE_CHECKOUT_MODAL = "TOGGLE_CHECKOUT_MODAL";
export const SET_CHECKOUT_MODAL_BACKDROP_TIMEOUT =
  "SET_CHECKOUT_MODAL_BACKDROP_TIMEOUT";
export const SET_AUTH_PROCESS_EMAIL = "SET_AUTH_PROCESS_EMAIL";
export const SET_CHECKOUT_PLAN_DURATION = "SET_CHECKOUT_PLAN_DURATION";
export const CHANGE_CHECKOUT_STEP = "CHANGE_CHECKOUT_STEP";

// designReducer
export const SET_INITIAL_SIZES = "SET_INITIAL_SIZES";
export const SET_INITIAL_SECTION = "SET_INITIAL_SECTION";
export const SET_INITIAL_TEMPLATE_LINK = "SET_INITIAL_TEMPLATE_LINK";
export const TOGGLE_REMAINING_DOWNLOADNS_MODAL =
  "TOGGLE_REMAINING_DOWNLOADNS_MODAL";
export const TOGGLE_DOWNLOAD_MODAL = "TOGGLE_DOWNLOAD_MODAL";
export const SET_IS_DOWNLOADING = "SET_IS_DOWNLOADING";
export const INCREMENT_NUMBER_OF_CHANGES = "INCREMENT_NUMBER_OF_CHANGES";
export const RESET_NUMBER_OF_CHANGES = "RESET_NUMBER_OF_CHANGES";
export const SET_SIDEPANEL_DEFAULT_OPEN = "SET_SIDEPANEL_DEFAULT_OPEN";
export const SET_FILE_DROPDOWN = "SET_FILE_DROPDOWN";
export const SET_HINT_STAGE = "SET_HINT_STAGE";
export const SET_ELEMENTS_PANEL_CATEGORY = "SET_ELEMENTS_PANEL_CATEGORY";

// dashboardReducer
export const CHANGE_DASHBOARD_SEARCH_TERM = "CHANGE_DASHBOARD_SEARCH_TERM";
export const TOGGLE_SELECTED_ITEMS = "TOGGLE_SELECTED_ITEMS";
export const SET_PROFILE_TOOLTIP = "SET_PROFILE_TOOLTIP";
