-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqBhQdFwD2e6mcjOJ
+Tfbscoyqmez5DovSdFYHTu1GmSgCgYIKoZIzj0DAQehRANCAATvcG6oiGoBOuBx
hwBBvaLcqYrLcI3pGdpJLSGVOUzCkj5KbjrKitkTznZYrNa3u0LzzkWrm5Ey/bi+
ind7lRII
-----END PRIVATE KEY-----